### ISSUE TITLE
Not working with pip>=10?

### ISSUE THREAD

**Issue by bedge** [Paradoxis/PIP-Module-Scanner#1]
using python 2.7:

> ❯ pip-module-scanner
> Traceback (most recent call last):
>   File "/Users/bedge/Virtualenvs/p2/bin/pip-module-scanner", line 11, in <module>
>     sys.exit(main())
>   File "/Users/bedge/Virtualenvs/p2/lib/python2.7/site-packages/pip_module_scanner/main.py", line 18, in main
>     scanner = Scanner(path=options.path, output=options.out)
>   File "/Users/bedge/Virtualenvs/p2/lib/python2.7/site-packages/pip_module_scanner/scanner.py", line 21, in __init__
>     self.libraries_installed = pip.get_installed_distributions()
> AttributeError: 'module' object has no attribute 'get_installed_distributions'

> ❯ pip --version
> pip 10.0.1 from /Users/bedge/Virtualenvs/p2/lib/python2.7/site-packages/pip (python 2.7)

This implies it's pip version >= 10 related: https://github.com/Miserlou/Zappa/issues/1471

FWIW, not working at all with python 3:

> ❯ pip-module-scanner
> Traceback (most recent call last):
>   File "/Users/bedge/Virtualenvs/p3/bin/pip-module-scanner", line 7, in <module>
>     from pip_module_scanner.main import main
>   File "/Users/bedge/Virtualenvs/p3/lib/python3.6/site-packages/pip_module_scanner/__init__.py", line 2, in <module>
>     import main
> ModuleNotFoundError: No module named 'main'
>

**Comment by Paradoxis** [comment]
Sorry for the late reply, totally missed your issue in my inbox. Fixed your issue, made it compatible with all versions of python from 2.7 to 3.6 and added unit tests for future stability.

You can update the package with:

```
$ pip install -U pip-module-scanner
```
