### ISSUE TITLE
Thoughts on updates to file selection and import name mapping

### ISSUE THREAD

**Issue by mshriver** [Paradoxis/PIP-Module-Scanner#2]
Hello owners, I've used your library to do some import scanning, but have subclassed within my project to make some updates to how the class scans for python files, how it scans imports for matches, and how it writes output files.

Right now my changes are a bit tailored to my project's use. Before abstracting my changes and adapting them to be an acceptable API change here, I wanted to get your opinion on changes in these areas.

1. Change the data structure of `Scanner.libraries_installed` to support different patterns in scanning
2. Support a blacklist of packages to ignore for `Scanner.libraries_installed`
3. Change to, or allow for, identifying files to scan via `git ls-files --full-name` instead of os.walk
4. Change to how os.walk behaves, ignoring dotfiles and blacklisting/whitelisting directories
5. Ability for output to be packages only, not versions, and to be sorted.
6. More efficient scanning loop in search_script
7. Support for mapping import names to project names (ex. `import git` vs `pip show GitPython`)
8. Better support for setting the regex expression, and a change to the default expression.

I would likely open about 4 separate PRs to cover these changes, as some of the items above can be done individually and some would depend on others for efficient changes.

Thanks!

**Comment by Paradoxis** [comment]
Hey, thanks for the feedback! Regarding the points you stated:

1. Could you elaborate more on this? I’m not quite sure what you’d want to do regarding pattern matching, I’d see that more as a post-use thing where you just pipe the output to grep if you’re looking for something specific (or are we talking file names?)

2. Seems like a good idea! It might be possible that false positives (like local package names) pop up, feel free to PR this!

3. I don’t think this is a good idea, the tool is designed for migrating old projects without a requirements file (or even without git for that matter) to a more structured environment (eg: github with ci/cd), using git would simply add a dependency and make the module less flexible in use overall for when you don’t have that binary on a production system

4. Sounds like a good idea, although making an option which re-includes dotfiles would be useful as it might be that a python file was temporarily renamed to a dotfile during development and the requirement might still be valid

5. Sounds like a good idea! Sorting seems like a no-brainer and wouldn’t hurt to do every time, but removing the verisons from the output sounds better as a toggle as in most cases you’d like the exact version pinned

6. Feel free to show what you mean, although rhe “yield from” keywords can’t be used here as it needs to work with older versions of Python too

7. Could you elaborate more on this? AFAIK the project already outputs the package name as it’s installed from pypi but I might be wrong, in which case that would be a bug :smile:

8. The only thing I can still think is missing from this is \_\_import\_\_() calls, what did you have in mind?

If you add PR’s could you also write test cases which support you changes? Thanks!

**Comment by mshriver** [comment]
Excellent, sounds like we're on the same page about most things.

1. The current import pattern does not accept `-` or `_` in package names, and several of my dependencies use this naming pattern.

7. In relation to 1, I found that packages such as `GitPython`, which are imported as `git`, were not recognized as pip-installed.  Same with `widgetastic.patternfly` package being imported as `widgetastic_patternfly`. Locally I just created a map between the import names and package names, but this is a quick and dirty solution, and I would prefer to include use of `importlib-metadata` in any PR I would open here.

3. I had done so by calling `git` via subprocess to use `ls-files`, and did not depend on GitPython.  This (and most of the suggestions I'm proposing here) would be an additional 'mode' that the Scanner could run in, without changing the current default behavior.

6. The current loop took quite some time to run against my codebase, and it came down to the nested for loops used, and where imported names are checked against the found libraries and installed packages.

8. Right now its set as an instance attribute, but no kwarg is accepted to modify it. If I want to change it for my use, I have to instantiate Scanner and then set `scanner.import_statement` directly.  Combined with some whitelist/blacklist of packages to include/ignore this may be fine as-is. Though I would still prefer to make it a class attribute and not an instance attribute, so that it may be set statically.

Given your feedback, I think I can open PR's and we can continue with more detailed discussions in those specific PR's.

Yes on including tests for changes!

**Comment by Paradoxis** [comment]
Awesome, feel free to add the PR's per change you have :)

1. Ah, didn't realize, feel free to PR this!
2. If you know how to, feel free to PR!
3. I meant a dependency on the `git` binary itself, is there a specific reason for doing it using `git` rather than `os.walk`? (eg: significant speed increase etc) I still don't really see specific reason to add this functionality
4. Ah, makes sense, how big is the codebase you're running it on? It could also be done by scanning it with multiple threads at once, feel free to suggest changes and show how much of a performance boost it is
5. Sounds good!

**Comment by Paradoxis** [comment]
@mshriver did you ever get around to implementing any of these features which I could merge or should I put the issue on hold? :)

**Comment by Paradoxis** [comment]
Putting on-hold due to inactivity
